{% set name = "arraylake-client" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arraylake_client-{{ version }}.tar.gz
  sha256: 6f8d06354141887113aef2284b4e5e2c0c5560bb798d35cca6ddad48c8d16c0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2
  entry_points:
    - arraylake = arraylake_client.cli.main:app

requirements:
  host:
    - python >=3.8,<3.11
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - __unix  # [unix]
    - python >=3.8,<3.11
    - aiobotocore >=2.4.0,<3.0.0
    - anyio >=3.6.1,<4.0.0
    - zarr >=2.14,<2.15
    - numpy >=1.20.0,<2.0.0
    - donfig >=0.7,<1.0
    - pydantic >=1.10.0,<2.0.0
    - httpx >=0.23.0,<1.0
    - pymongo >=4.2.0,<5.0.0
    - cachetools >=5.3.0,<6.0.0
    - structlog >=23.1.0,<24.0.0
    - uvloop  # [unix]
    - email_validator
    - types-aiobotocore-s3
    - typer
    - ruamel.yaml
  run_constrained:
    - ruamel.yaml >=0.17,<1.0
    - typer >=0.6.1,<1.0
    - rich >=12.6,<14.0
    - fsspec >=2022.11.0
    - kerchunk >=0.1,<1.0
    - h5py >=3.7.0,<4.0.0
    - s3fs >=2022.11.0
    - ipytree >=0.2.2,<1.0

test:
  imports:
    - arraylake_client
  commands:
    - pip check
    - arraylake --version
  requires:
    - pip

about:
  home: https://docs.earthmover.io
  summary: Python client for ArrayLake
  license: 'Unlicense'

extra:
  recipe-maintainers:
    - jhamman
    - rabernat
    - olimcc
